### ISSUE TITLE
Horizontal lines on the HTML landing page with Safari

### ISSUE THREAD

**Issue by EricL2017** [creativetimofficial/tailwind-starter-kit#10]
Hi, there are horizontal lines appearing before/after sections on the HTML landing page. This happens on Safari version 14.0. It also appears randomly, depending on the size of the safari window. Attached is an example of the issue, which is easy to reproduce.
<img width="1113" alt="Screen Shot 2020-09-23 at 4 03 34 PM" src="https://user-images.githubusercontent.com/28696680/94064645-fc2ef600-fdb7-11ea-89d8-56ee26271ccd.png">

**Comment by EINazare** [comment]
Hello there, @EricL2017 ,

At the moment we do not have a fix for this.
From what we can tell, that line only appears when resizing the window, we think it may be a bug from the actual browser.
A quick fix could be the to change the following line:
```
<svg class="absolute bottom-0 overflow-hidden" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" version="1.1" viewBox="0 0 2560 100" x="0" y="0">
```
To
```
<svg class="absolute bottom-0 overflow-hidden -mb-1" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" version="1.1" viewBox="0 0 2560 100" x="0" y="0">
```
This will make the fancy skew go downwards a bit (~4px), this means that it should cover the 1px black line that you see.

Let me know if that solved your issue.

Best,
Manu

**Comment by EricL2017** [comment]
Hi Manu,

Thanks for your quick response. I applied the changes that you suggested, however it does not fix the issue. See attached the updated HTML landing page, for reference. 

Thanks!
Eric

[landing.html.zip](https://github.com/creativetimofficial/tailwind-starter-kit/files/5277409/landing.html.zip)

**Comment by ryanwinchester** [comment]
I also see the line in Firefox and not just from resizing the page.

**Comment by ryanwinchester** [comment]
Also, I think the `-mb-1` fix _would_ work, but I don't think that class is included in the provided compiled tailwindcss file.

**Comment by ryanwinchester** [comment]
I added `style="margin-bottom:-1px;"` to each SVG and it _mostly_ fixed it. The top one still had the line almost randomly. And it could disappear and reappear when scrolling.

When I removed `transform: translateZ(0px);`  it seems to have disappeared completely.
