### ISSUE TITLE
Clicking anywhere in the modal closes it

### ISSUE THREAD

**Issue by giraffesyo** [creativetimofficial/tailwind-starter-kit#16]
Hey, awesome project!

I was checking out the modal you have here and noticed clicking anywhere inside the modal will close it.

https://www.creative-tim.com/learning-lab/tailwind-starter-kit/documentation/react/modals/regular

**Comment by EINazare** [comment]
Hello there, @giraffesyo ,

Yes, that is because of this code:
```
          <div
            className="justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none"
            onClick={() => setShowModal(false)}
          >
```
Just replace it with:
```
          <div
            className="justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none"
          >
```
And you should be good to go.

Best,
Manu
