### ISSUE TITLE
navbar-expand-lg class does not exist in any of the imported css files

### ISSUE THREAD

**Issue by skiabox** [creativetimofficial/tailwind-starter-kit#19]
Hello guys.
It seems that you've forgotten this class, maybe from a bootstrap code copy paste, so I believe that you can safely delete it!
Keep up the good work!

**Comment by EINazare** [comment]
Hey there, @skiabox ,

Thanks for letting us know.
We'll update this project in the following month and we'll delete that.
We'll also update to Tailwind v2 😁 .
Please leave the issue open.

Best,
Manu
