### ISSUE TITLE
Is it possible to compile the stylesheet by ourself instead of using the cdn provided one?

### ISSUE THREAD

**Issue by rmahmood19** [creativetimofficial/tailwind-starter-kit#21]
Hi, 
First of all,  thanks for this awesome product. As it says in the intro, It does not change or add any CSS to the already one from TailwindCSS, I was wondering will it be possible compile the css file by ourself.
I am trying to use it on a laravel project, using laravel mix to compile my own css file form standard tailwind installation. Since it is using the standard tailwind classes, should the theme work exactly same if i compile it form standard tailwind install
Thanks for your time.

**Comment by EINazare** [comment]
Hey there, @rmahmood19 ,

Please follow the instruction here: https://www.creative-tim.com/learning-lab/tailwind-starter-kit/documentation/build-tools

Let me know if that helped.

Best,
Manu
