### ISSUE TITLE
MIT Licensed or not?

### ISSUE THREAD

**Issue by mhitza** [creativetimofficial/tailwind-starter-kit#22]
The repository is marked with the MIT license, but the Resources section at the end of the README.md links to a License Agreement page, which is a proprietary license.

**Comment by EINazare** [comment]
Hello there, @mhitza ,

Thanks for noticing this. I've forwarded your issue to my managers.

Best,
Manu

**Comment by mhitza** [comment]
Hey @EINazare I see you closed this issue and removed the License Agreement link. But you only did so within a single README, whereas all the README's within the repository have the same link (probably a template README that was copy pasted between them, if I were to guess).
