### ISSUE TITLE
Click on non-React examples on website lead to homepage

### ISSUE THREAD

**Issue by owzim** [creativetimofficial/tailwind-starter-kit#24]
Example: https://www.creative-tim.com/learning-lab/tailwind-starter-kit/documentation/react/tabs/text

If I click on any other language/framework than React, I get redirected to the home page. 

![image](https://user-images.githubusercontent.com/1720088/109154992-58cf7c00-776f-11eb-9653-75e8b1dce005.png)

Tested in latest FF and Chrome.

This issue exists on all examples.

**Comment by EINazare** [comment]
Hello there, @owzim ,

Thanks for letting us know.
We've solved the issue.

Happy Hacking!

Best,
Manu
