### ISSUE TITLE
Download links under README are not working

### ISSUE THREAD

**Issue by kyooreasmayk** [creativetimofficial/tailwind-starter-kit#34]
- Download links under Quick Start and Resources section under README file are not working.
- It seems like it still have the old URL of the "master" branch.: https://codeload.github.com/creativetimofficial/tailwind-starter-kit/zip/master
- I was able to make it work through: https://codeload.github.com/creativetimofficial/tailwind-starter-kit/zip/main

**Comment by marqbeniamin** [comment]
@kyooreasmayk I fixed that. Thank you for your contribution!
