### ISSUE TITLE
Components Not Accesable? 

### ISSUE THREAD

**Issue by alteredorange** [creativetimofficial/tailwind-starter-kit#4]
I don't see any of the components included (i.e like[ alerts](https://www.creative-tim.com/learning-lab/tailwind-starter-kit/#/documentation/alerts)). Am I just blind? Thanks for the awesome components!

**Comment by EINazare** [comment]
Hello there, @alteredorange ,

Thank you for your interest in working with our project.
At the moment, on this repository we only offer the Pages found on: https://www.creative-tim.com/learning-lab/tailwind-starter-kit#/documentation/landing
For the components, you need to take them from their docs pages: https://www.creative-tim.com/learning-lab/tailwind-starter-kit#/documentation/alerts

I'll take some time these days/weeks and add those components on this repository as well, thank you for your feedback.

Best,
Manu

**Comment by alteredorange** [comment]
Good to know, keep up the great work!
