### ISSUE TITLE
Plans on check tailwind.config.js into source control?

### ISSUE THREAD

**Issue by elkevinwolf** [creativetimofficial/tailwind-starter-kit#6]
Hi everyone! First of all I want to say thanks and congratulate you on the awesome work on putting up this starter kit, I love how it looks and I am looking forward to implementing it on my projects.

However, I'm wondering if there is any plan on checking into GitHub the `tailwind.config.js` file, on that way developers can tweak some stuff according to their needs.

Again, thanks a lot for taking the time on building such an awesome template! <3

**Comment by EINazare** [comment]
Hello there, @kevinwolfdev ,

Thank you for your interest in working with our project and for your kind words.
We are unaware of what you are asking here: `However, I'm wondering if there is any plan on checking into GitHub the tailwind.config.js file, on that way developers can tweak some stuff according to their needs.`.
Are you looking for this:
```
module.exports = {
  variants: [
    "responsive",
    "group-hover",
    "focus-within",
    "first",
    "last",
    "odd",
    "even",
    "hover",
    "focus",
    "active",
    "visited",
    "disabled"
  ],
  plugins: [require("@tailwindcss/custom-forms")]
};
```

Best,
Manu

**Comment by kevinwolfdev** [comment]
Thanks for your response, @EINazare. My question was specifically for the whole config (including definition for all the fonts, colors, spacing, etc), just in case a user wants to modify the color palette or adjust some stuff.

The full config file can be generated by running `tailwind init —full`

**Comment by EINazare** [comment]
Hello there, @kevinwolfdev ,

We haven't used the full generated config file, we used the above one instead.

Best,
Manu
