### ISSUE TITLE
Sidebar reversed

### ISSUE THREAD

**Issue by AndreSpecker** [creativetimofficial/tailwind-starter-kit#7]
Hello, I configured to use tailwind like this:
screens: {  'xl': {  'max': '1279px'},
            'lg': { 'max': '1023px'  },
            'md': { 'max': '767px' },
            'sm': { 'max': '639px' },
https://tailwindcss.com/docs/breakpoints/#max-width-breakpoints

But now the site sidebar has reversed, in smartphone it shows the sidebar, and on desktop it disappears, what I have do to do change to work?
 
Thanks.

**Comment by EINazare** [comment]
Hello there, @AndreSpecker ,

Thank you for your interest in working with our products.
At the moment we do not have a solution for your issue, please revert the changes to our original code.

Best,
Manu
